name: Tickets  # 自定义工作流名称
on:
  schedule:
    - cron: '*/5 * * * *'  # 每10分钟检查一次（避免高频请求）
  workflow_dispatch:  # 允许手动触发

jobs:
  check-tickets:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Tickets
        uses: mooyoul/melon-ticket-actions@v1.1.0  # 使用最新版本
        with:
          product-id: 211313  # 替换为你的Secrets变量名
          schedule-id: SC0001
          seat-id: 1_0  # 可选，若需指定座位区域则保留并替换为你的seat-id
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: '211313有票！速抢：https://global.melon-ticket.com/product/211313'
